const ERROR_CODES = {
    // Validation
    VALIDATION_ERROR: "VALIDATION_ERROR",
    INVALID_PAGE: "INVALID_PAGE",
    INVALID_LIMIT: "INVALID_LIMIT",

    // User
    USER_NOT_FOUND: "USER_NOT_FOUND",
    USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
    INVALID_USER_ID: "INVALID_USER_ID",

    // Product
    PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
    PRODUCT_SKU_ALREADY_EXISTS: "PRODUCT_SKU_ALREADY_EXISTS",
    PRODUCT_NOT_ACTIVE: "PRODUCT_NOT_ACTIVE",
    INVALID_PRODUCT_ID: "INVALID_PRODUCT_ID",
    INVALID_PRODUCTS: "INVALID_PRODUCTS",

    // Order
    ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
    INVALID_ORDER_ID: "INVALID_ORDER_ID",
    INVALID_ORDER_ITEMS: "INVALID_ORDER_ITEMS",
    INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",

    // System
    DUPLICATE_KEY: "DUPLICATE_KEY",
    INTERNAL_ERROR: "INTERNAL_ERROR"
};

module.exports = ERROR_CODES;
